### ISSUE TITLE
cannot use source or eval in Rserve.conf or in backend$start as additional args

### ISSUE THREAD

**Issue by kevinnowland** [rexyai/RestRserve#192]
Hello! I have been trying to take advantage of pre-loading data
via the `source` and / or `eval` arguments in `Rserve` for an 
app that is using `RestRserve`. The ideas was to prevent memory spikes
when receiving many concurrent requests by pre-loading objects before
the forking happens.

The following set of files give an example setup that is not working
as I would have thought. This is using `RestRserve_1.1.1`.

## Dockerfile

```
FROM r-base:4.1.2

RUN R -e "install.packages('RestRserve')"
COPY server.R .

CMD ["Rscript", "server.R"]
```

which is built with the command

```
docker build -t rserve:test .
```

## server.R

```
library("RestRserve")

ping <- function(.req, .res)
{
    .res$set_status_code(200L)
    .res$set_body(jsonlite::toJSON("OK"))
    .res$set_content_type("application/json")
    
    # Line below does not work if uncommented
    # print(x)
}

app <- Application$new()

## register endpoints and corresponding handlers
app$add_get(path = "/ping", FUN=ping)

backend = BackendRserve$new()

backend$start(app, http_port = 8080)

# I have also tried the below commented line to try to avoid the 
# config file entirely:
# backend$start(app, http_port = 8080, source="/startup.R")

# this also does not print anything if uncommented
# backend$start(app, http_port = 8080, eval="print('hello')")
```

## docker-compose.yaml

I have been starting the image using `docker-compose up` with the following `docker-compose.yaml` file
which loads `Rserve.conf` to `/etc/Rserve.conf` (tried also as `Rserv.conf`).

```
version: '3.7'
services:
    test:
      image: rserve:test
      logging:
          options:
              max-size: 10m
              max-file: "3"
      ports:
        - "8181:8080"
      volumes:
        - ./server.R:/server.R
        - ./startup.R:/startup.R
        - ./Rserve.conf:/etc/Rserve.conf
```

The server starts up fine.

## `Rserve.conf` or `Rserv.conf`

Then I am trying to configure `Rserve` using the following
file which gets put into the image at runtime to `/etc/Rserve.conf`
(I have also tried `/etc/Rserv.conf` without the e):

```
source /startup.R
```

Which should be referencing the following file

## `startup.R`

```
print("\n\n\nhello\n\n\n")

x <- 1
```

However, I cannot see either the statement getting printed in the
docker-compose logs and cannot use the variable `x` in the ping route, for
example.

Any help would be appreciated. Thank you!
